---
layout: home
title: My website
subtitle: This is where I will tell my friends way too much about me
output: html_document
---


```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbump)
library(jsonlite)
library(knitr)
library(gt)
library(DT)
library(formattable)
library(forcats)
library(kableExtra)
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
# Assuming you have your plot saved as 'plot' in your environment
data <- fromJSON("C:/Users/augus/Desktop/pindespil/data1.json")


expand_json_to_df <- function(data) {
  
  # Initialize an empty list to store results
  expanded_rows <- list()
  
  # Loop through each item in the list (each JSON object)
  for (i in seq_along(data$pindespil_id)) {
    # Get the current values
    pindespil_id <- data$pindespil_id[[i]]
    dato <- data$dato[[i]]
    vindende_hold <- data$vindende_hold[[i]]
    tabende_hold <- data$tabende_hold[[i]]
    spiltype <- data$spiltype[[i]]
    trojer <- data$trojer[[i]]
    joker <- data$joker[[i]]
    
    # Find the maximum length between vindende_hold and tabende_hold
    max_len <- max(length(vindende_hold), length(tabende_hold))
    
    # Expand each vector to the same length (padding with NA if needed)
    vindende_hold <- c(vindende_hold, rep(NA, max_len - length(vindende_hold)))
    tabende_hold <- c(tabende_hold, rep(NA, max_len - length(tabende_hold)))
    
    # Repeat pindespil_id and dato to match the length
    pindespil_id <- rep(pindespil_id, max_len)
    dato <- rep(dato, max_len)
    spiltype <- rep(spiltype, max_len)
    trojer <- rep(trojer, max_len)
    joker <- rep(joker, max_len)
    # Combine the expanded rows into a data frame
    expanded_rows[[i]] <- data.frame(pindespil_id, 
                                     dato, 
                                     vindende_hold, 
                                     tabende_hold, 
                                     spiltype,
                                     trojer,
                                     joker, 
                                     stringsAsFactors = FALSE)
  }
  
  # Bind all the expanded rows into a single data frame
  expanded_df <- do.call(rbind, expanded_rows)
  
  return(expanded_df)
}

df_expanded <- expand_json_to_df(data)

test <- df_expanded %>% 
  pivot_longer(cols = c(vindende_hold, tabende_hold),
              names_to = "udfald",
              values_to = "spiller")

df <- data.frame(var = c(
  "August, gammel, forsvar",
  "Agge, gammel, midtbane",
  "Albert, gammel, forsvar",
  "Aland, gammel, keeper",
  "Banda, ung, angreb",
  "Bondo, gammel, midtbane",
  "Biele, gammel, midtbane",
  "Claes, gammel, forsvar",
  "Dalby, gammel, keeper",
  "Fey, gammel, forsvar",
  "Grube, gammel, forsvar",
  "Haris, ung, angreb",
  "Gulle, gammel, midtbane",
  "Lau, ung, forsvar",
  "Max, ung, midtbane",
  "Nico, ung, forsvar",
  "Nick, gammel, angreb",
  "Mikkel, gammel, angreb",
  "Noel, gammel, midtbane",
  "Shimal, gammel, angreb",
  "Semir, ung, midtbane",
  "Trane, gammel, angreb",
  "Kav, gammel, forsvar",
  "Walther, ung, midtbane",
  "Mathias, ung, midtbane",
  "Christian, gammel, midtbane",
  "Jokke, gammel, forsvar",
  "Thomas, ung, angreb",
  "Alexander, ung, angreb"
  )) %>% 
  separate(var, into = c("name", "age", "position"), sep = ", ", remove = TRUE)
test2 <- test %>% 
  left_join(df, by = c("spiller"="name"))
```



```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=8}
test2 %>% 
  filter(udfald == "vindende_hold", !is.na(spiller), spiller != "") %>% 
  group_by(spiller) %>%
  summarise(Pinde = n(), position = first(position), age = first(age), .groups = 'drop') %>% 
  ggplot(aes(fct_reorder(spiller, Pinde), Pinde)) +  # Order by Pinde in ascending order
  geom_segment(aes(x = fct_reorder(spiller, Pinde), xend = fct_reorder(spiller, Pinde),
                   y = 0, yend = Pinde, color = position),
               lwd = 2) +
  geom_point(aes(shape = age, fill = position, color = position), size = 7.5) +
  geom_text(aes(label = Pinde), color = "white", size = 4) +
  scale_shape_manual(values = c(21, 22), name = " ") +
  scale_x_discrete(name = "")+
  geom_hline(yintercept = 0) +
  coord_flip() +  # This flips the axes
  theme_light() + 
  theme(legend.title = element_blank())
```

